In [1]:
import numpy as np

### Single output example

In [2]:
a = np.random.randn(5)
a

array([-0.36710061, -0.67012695,  0.49512674,  1.48306992, -0.68713561])

In [4]:
expa = np.exp(a)
expa

array([ 0.69273995,  0.51164362,  1.64070617,  4.40645237,  0.50301484])

In [5]:
smax = expa / expa.sum()
smax

array([ 0.08933327,  0.06597974,  0.21157961,  0.56824038,  0.064867  ])

### Output Array

In [7]:
A = np.random.randn(100, 5)

In [8]:
expA = np.exp(A)

In [9]:
smaxA = expA / expA.sum(axis = 1, keepdims = True)

In [10]:
smaxA[:10]

array([[ 0.09271716,  0.3972813 ,  0.05794322,  0.15209545,  0.29996287],
       [ 0.19699098,  0.05092447,  0.52574356,  0.15210514,  0.07423585],
       [ 0.03413873,  0.06036705,  0.38054791,  0.41957858,  0.10536773],
       [ 0.32428827,  0.24116123,  0.29523753,  0.12752339,  0.01178958],
       [ 0.01245263,  0.20043907,  0.18316159,  0.07075657,  0.53319014],
       [ 0.19419089,  0.22542441,  0.43613689,  0.04191068,  0.10233713],
       [ 0.06967034,  0.44966736,  0.27776903,  0.07863823,  0.12425505],
       [ 0.13506202,  0.37811436,  0.16611052,  0.18141971,  0.13929339],
       [ 0.15599493,  0.08032871,  0.04777285,  0.66634444,  0.04955908],
       [ 0.14047899,  0.13958802,  0.13179204,  0.54410667,  0.04403428]])