In [22]:
import numpy as np
import torch

In [2]:
x = torch.empty(5, 3)
x

tensor([[  0.0000,   0.0000,   0.0000],
        [  0.0000,  -7.5000,   0.0000],
        [ -7.5734,   0.0000,  -6.5334],
        [  0.0000, -72.2428,   0.0000],
        [ -6.5571,   0.0000, -72.1355]])

In [3]:
x = torch.rand(3, 5)
x

tensor([[ 0.3931,  0.8113,  0.7901,  0.6937,  0.5022],
        [ 0.0676,  0.8355,  0.9802,  0.7170,  0.5290],
        [ 0.8704,  0.6978,  0.3664,  0.2435,  0.1493]])

In [5]:
x = torch.zeros(2, 3, dtype=torch.long)
x

tensor([[ 0,  0,  0],
        [ 0,  0,  0]])

In [8]:
x = torch.tensor([5.4, 3])
x

tensor([ 5.4000,  3.0000])

In [9]:
x = x.new_ones(5, 3, dtype=torch.double)
x

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)

In [10]:
x = torch.randn_like(x, dtype=torch.float)
x

tensor([[-0.4475,  1.2370,  2.0512],
        [-0.2260, -0.3147,  1.2041],
        [ 0.0659, -0.0098, -1.6345],
        [-0.3508, -1.5078,  0.4003],
        [ 0.8141, -2.7996,  0.7986]])

In [11]:
x.size()

torch.Size([5, 3])

# Operations

In [12]:
y = torch.rand(5, 3)
x + y

tensor([[ 0.0969,  2.0209,  2.8436],
        [ 0.2585,  0.2633,  1.9023],
        [ 0.2461,  0.3043, -1.2947],
        [-0.1921, -0.9078,  0.8342],
        [ 0.9970, -2.2034,  1.7613]])

In [13]:
torch.add(x, y)

tensor([[ 0.0969,  2.0209,  2.8436],
        [ 0.2585,  0.2633,  1.9023],
        [ 0.2461,  0.3043, -1.2947],
        [-0.1921, -0.9078,  0.8342],
        [ 0.9970, -2.2034,  1.7613]])

In [14]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
result

tensor([[ 0.0969,  2.0209,  2.8436],
        [ 0.2585,  0.2633,  1.9023],
        [ 0.2461,  0.3043, -1.2947],
        [-0.1921, -0.9078,  0.8342],
        [ 0.9970, -2.2034,  1.7613]])

In [15]:
y.add_(x)
y

tensor([[ 0.0969,  2.0209,  2.8436],
        [ 0.2585,  0.2633,  1.9023],
        [ 0.2461,  0.3043, -1.2947],
        [-0.1921, -0.9078,  0.8342],
        [ 0.9970, -2.2034,  1.7613]])

In [16]:
x[:, 1]

tensor([ 1.2370, -0.3147, -0.0098, -1.5078, -2.7996])

In [18]:
x = torch.randn(4, 4)
y = x.view(16) # reshape
z = x.view(-1, 8) # as reshape in np
print(y.size(), z.size()) # size not shape!

torch.Size([16]) torch.Size([2, 8])


In [19]:
x = torch.randn(1)
print(x, x.item())

tensor([-0.2454]) -0.24544978141784668


### Docs for Tensor Operations:
https://pytorch.org/docs/stable/torch.html

# Numpy Bridge

In [21]:
a = torch.ones(5)
a

tensor([ 1.,  1.,  1.,  1.,  1.])

In [24]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [25]:
a.add_(1)
a, b

(tensor([ 2.,  2.,  2.,  2.,  2.]), array([2., 2., 2., 2., 2.], dtype=float32))

# Np-torch Conversion

In [26]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
a, b

(array([2., 2., 2., 2., 2.]),
 tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64))

# CUDA Tensors

In [27]:
if torch.cuda.is_available():
    device = torch.device('cuda')         # a CUDA devise obj
    y = torch.ones_like(x, device=device) # directly create tensor on GPU
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to('cpu', torch.double))
else:
    print('CUDA not available')

CUDA not available
