In [1]:
import numpy as np
import tensorflow as tf

### Squared Difference Between Two Tensors

In [2]:
x = [1, 3, 5, 7, 11]
y = 5
tf.math.squared_difference(x, y)

<tf.Tensor: id=2, shape=(5,), dtype=int32, numpy=array([16,  4,  0,  4, 36], dtype=int32)>

In [3]:
# functionally equivalent to:
x = np.array(x)
(5 - x)**2

array([16,  4,  0,  4, 36])

### Mean

In [4]:
numbers = tf.constant([[4., 5.], [7., 3.]])
tf.reduce_mean(input_tensor=numbers) # mean of all cells

<tf.Tensor: id=5, shape=(), dtype=float32, numpy=4.75>

In [5]:
# col-wise
tf.reduce_mean(input_tensor=numbers, axis=0)

<tf.Tensor: id=7, shape=(2,), dtype=float32, numpy=array([5.5, 4. ], dtype=float32)>

In [6]:
# col-wise
tf.reduce_mean(input_tensor=numbers, axis=0, keepdims=True)

<tf.Tensor: id=9, shape=(1, 2), dtype=float32, numpy=array([[5.5, 4. ]], dtype=float32)>

In [7]:
# row-wise
tf.reduce_mean(input_tensor=numbers, axis=1)

<tf.Tensor: id=11, shape=(2,), dtype=float32, numpy=array([4.5, 5. ], dtype=float32)>

In [8]:
# row-wise
tf.reduce_mean(input_tensor=numbers, axis=1, keepdims=True)

<tf.Tensor: id=13, shape=(2, 1), dtype=float32, numpy=
array([[4.5],
       [5. ]], dtype=float32)>

### Random Values
Normal

In [9]:
tf.random.normal(shape=(3, 2), 
                 mean=10, 
                 stddev=2, 
                 dtype=tf.float32, 
                 seed=None, 
                 name=None)

<tf.Tensor: id=19, shape=(3, 2), dtype=float32, numpy=
array([[ 9.114962 ,  9.2678795],
       [11.913335 ,  9.294933 ],
       [ 8.152638 ,  7.668091 ]], dtype=float32)>

In [10]:
rnorm = tf.random.normal((3, 2), mean=10., stddev=3.)
rnorm

<tf.Tensor: id=25, shape=(3, 2), dtype=float32, numpy=
array([[12.160835 ,  8.977037 ],
       [ 4.1770787, 12.660565 ],
       [ 8.382292 , 11.1526575]], dtype=float32)>

Uniform

In [11]:
u1 = tf.random.uniform((2, 2), minval=0, maxval=10, dtype=tf.int32)
u1

<tf.Tensor: id=29, shape=(2, 2), dtype=int32, numpy=
array([[7, 7],
       [7, 0]], dtype=int32)>

In [12]:
dice1 = tf.Variable(
    tf.random.uniform((10, 1), minval=1, maxval=7, dtype=tf.int32))
dice2 = tf.Variable(
    tf.random.uniform((10, 1), minval=1, maxval=7, dtype=tf.int32))
dice_sum = dice1 + dice2
result = tf.concat(values=[dice1, dice2, dice_sum], axis=1)
result # [d1, d2, sum] x10

<tf.Tensor: id=57, shape=(10, 3), dtype=int32, numpy=
array([[ 5,  2,  7],
       [ 4,  3,  7],
       [ 2,  1,  3],
       [ 6,  6, 12],
       [ 5,  1,  6],
       [ 4,  6, 10],
       [ 1,  2,  3],
       [ 6,  1,  7],
       [ 1,  4,  5],
       [ 5,  3,  8]], dtype=int32)>

### Argmin, Argmax

In [13]:
# 1D 
t5 = tf.constant([2, 11, 5, 42, 7, 19, -6, -11, 29])
t5

<tf.Tensor: id=58, shape=(9,), dtype=int32, numpy=array([  2,  11,   5,  42,   7,  19,  -6, -11,  29], dtype=int32)>

In [14]:
i = tf.argmax(t5)
j = tf.argmin(t5)
i, j

(<tf.Tensor: id=60, shape=(), dtype=int64, numpy=3>,
 <tf.Tensor: id=62, shape=(), dtype=int64, numpy=7>)

In [15]:
t5[i], t5[j]

(<tf.Tensor: id=69, shape=(), dtype=int32, numpy=42>,
 <tf.Tensor: id=76, shape=(), dtype=int32, numpy=-11>)

In [16]:
t6 = tf.reshape(t5, [3, 3])
t6

<tf.Tensor: id=78, shape=(3, 3), dtype=int32, numpy=
array([[  2,  11,   5],
       [ 42,   7,  19],
       [ -6, -11,  29]], dtype=int32)>

In [17]:
# Row max
i = tf.argmax(t6, axis=0).numpy()
i

array([1, 0, 2])

### Checkpoints for Saving/Restoring Tensors

In [18]:
variable = tf.Variable([[1, 3, 5, 7],
                        [2, 4, 6, 8]])
checkpoint = tf.train.Checkpoint(var=variable)
save_path = checkpoint.save('./vars')
variable.assign([[0, 0, 0, 0], 
                 [0, 0, 0, 0]])
variable

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)>

In [19]:
checkpoint.restore(save_path)
variable

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[1, 3, 5, 7],
       [2, 4, 6, 8]], dtype=int32)>

### `tf.function`

In [20]:
def f1(x, y):
    return tf.reduce_mean(input_tensor=tf.multiply(x**2, 5) + y**2)

f2 = tf.function(f1)

In [21]:
x = tf.constant([4., -5.])
y = tf.constant([2., 3.])

f2(x, y).numpy()

109.0

In [22]:
f1(x, y).numpy()

109.0