In [1]:
import numpy as np
import tensorflow as tf

### Squared Difference Between Two Tensors

In [2]:
x = [1, 3, 5, 7, 11]
y = 5
tf.math.squared_difference(x, y)

<tf.Tensor: id=2, shape=(5,), dtype=int32, numpy=array([16,  4,  0,  4, 36], dtype=int32)>

In [3]:
# functionally equivalent to:
x = np.array(x)
(5 - x)**2

array([16,  4,  0,  4, 36])

### Mean

In [4]:
numbers = tf.constant([[4., 5.], [7., 3.]])
tf.reduce_mean(input_tensor=numbers) # mean of all cells

<tf.Tensor: id=5, shape=(), dtype=float32, numpy=4.75>

In [5]:
# col-wise
tf.reduce_mean(input_tensor=numbers, axis=0)

<tf.Tensor: id=7, shape=(2,), dtype=float32, numpy=array([5.5, 4. ], dtype=float32)>

In [6]:
# col-wise
tf.reduce_mean(input_tensor=numbers, axis=0, keepdims=True)

<tf.Tensor: id=9, shape=(1, 2), dtype=float32, numpy=array([[5.5, 4. ]], dtype=float32)>

In [7]:
# row-wise
tf.reduce_mean(input_tensor=numbers, axis=1)

<tf.Tensor: id=11, shape=(2,), dtype=float32, numpy=array([4.5, 5. ], dtype=float32)>

In [8]:
# row-wise
tf.reduce_mean(input_tensor=numbers, axis=1, keepdims=True)

<tf.Tensor: id=13, shape=(2, 1), dtype=float32, numpy=
array([[4.5],
       [5. ]], dtype=float32)>

### Random Values
Normal

In [9]:
tf.random.normal(shape=(3, 2), 
                 mean=10, 
                 stddev=2, 
                 dtype=tf.float32, 
                 seed=None, 
                 name=None)

<tf.Tensor: id=19, shape=(3, 2), dtype=float32, numpy=
array([[ 9.975672,  9.985079],
       [ 8.328375, 10.612458],
       [ 9.954831,  9.84242 ]], dtype=float32)>

In [11]:
rnorm = tf.random.normal((3, 2), mean=10., stddev=3.)
rnorm

<tf.Tensor: id=31, shape=(3, 2), dtype=float32, numpy=
array([[10.8481   , 16.418352 ],
       [ 6.4090624, 11.223981 ],
       [11.494238 ,  8.937645 ]], dtype=float32)>

Uniform

In [12]:
u1 = tf.random.uniform((2, 2), minval=0, maxval=10, dtype=tf.int32)
u1

<tf.Tensor: id=35, shape=(2, 2), dtype=int32, numpy=
array([[3, 0],
       [0, 1]], dtype=int32)>

In [15]:
dice1 = tf.Variable(
    tf.random.uniform((10, 1), minval=1, maxval=7, dtype=tf.int32))
dice2 = tf.Variable(
    tf.random.uniform((10, 1), minval=1, maxval=7, dtype=tf.int32))
dice_sum = dice1 + dice2
result = tf.concat(values=[dice1, dice2, dice_sum], axis=1)
result # [d1, d2, sum] x10

<tf.Tensor: id=117, shape=(10, 3), dtype=int32, numpy=
array([[ 2,  3,  5],
       [ 1,  5,  6],
       [ 2,  5,  7],
       [ 6,  5, 11],
       [ 4,  1,  5],
       [ 6,  1,  7],
       [ 4,  6, 10],
       [ 5,  2,  7],
       [ 6,  3,  9],
       [ 2,  1,  3]], dtype=int32)>