In [1]:
import tensorflow as tf

In [2]:
print(f'TF Version: {tf.__version__}')
print(f'Eager Execution: {tf.executing_eagerly}')
print(f'Keras Version: {tf.keras.__version__}')

TF Version: 2.0.0
Eager Execution: <function executing_eagerly at 0x13d5a6170>
Keras Version: 2.2.4-tf


### Eager Execution (= Default)

In [3]:
var = tf.Variable([3, 3])
if tf.test.is_gpu_available():
    print('Running on GPU')
    print('GPU #0?')
    print(var.device.endswith('GPU:0'))
else:
    print('Running on CPU')

Running on CPU


### Declaring Eager Vars

In [4]:
t0 = 24 # python var
t1 = tf.Variable(42) # scalar/rank-0 tensor
t2 = tf.Variable([[0., 1., 2.],
                  [3., 4., 5.],
                  [6., 7., 8.],
                  [9., 0., 1.]]) # matrix/rank-2 tensor
t0, t1, t2

(24,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>,
 <tf.Variable 'Variable:0' shape=(4, 3) dtype=float32, numpy=
 array([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.],
        [9., 0., 1.]], dtype=float32)>)

In [5]:
f64 = tf.Variable(89, dtype=tf.float64)
f64

<tf.Variable 'Variable:0' shape=() dtype=float64, numpy=89.0>

In [6]:
f64.dtype

tf.float64

In [7]:
f1 = tf.Variable(89.)
print(f1)

f1.assign(98.)
f1

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=89.0>


<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=98.0>

### Declaring TF Constants

In [8]:
c1 = tf.constant(42)
print(c1)

c1.numpy()

tf.Tensor(42, shape=(), dtype=int32)


42

In [9]:
unit = tf.constant(1, dtype=tf.int64)
unit

<tf.Tensor: id=43, shape=(), dtype=int64, numpy=1>

### Shaping a Tensor

In [11]:
t2 = tf.Variable([[[0., 1., 2.],
                   [3., 4., 5.]],
                  [[6., 7., 8.],
                   [9., 0., 1.]]])
t2.shape

TensorShape([2, 2, 3])

In [12]:
r1 = tf.reshape(t2, [2, 6])
r1

<tf.Tensor: id=60, shape=(2, 6), dtype=float32, numpy=
array([[0., 1., 2., 3., 4., 5.],
       [6., 7., 8., 9., 0., 1.]], dtype=float32)>

In [13]:
r2 = tf.reshape(t2, [1, 12])
r2

<tf.Tensor: id=63, shape=(1, 12), dtype=float32, numpy=array([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9., 0., 1.]], dtype=float32)>

In [16]:
r3 = tf.reshape(t2, [12])
r3

<tf.Tensor: id=72, shape=(12,), dtype=float32, numpy=array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9., 0., 1.], dtype=float32)>

In [20]:
r4 = tf.reshape(t2, [4, -1, 3])
r4

<tf.Tensor: id=83, shape=(4, 1, 3), dtype=float32, numpy=
array([[[0., 1., 2.]],

       [[3., 4., 5.]],

       [[6., 7., 8.]],

       [[9., 0., 1.]]], dtype=float32)>

### Rank/Dimension of a Tensor

In [21]:
tf.rank(t2) # rank is the numpy= value

<tf.Tensor: id=85, shape=(), dtype=int32, numpy=3>

### Specifying Tensor Elements

In [23]:
t3 = t2[1, 0, 2]
t3

<tf.Tensor: id=91, shape=(), dtype=float32, numpy=8.0>